name: MLOps Pipeline

on: [push]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Run tests
      working-directory: ./
      run: |
        pytest tests/

  train_and_quantize:
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create models directory
      run: mkdir -p models
    - name: Train and quantize model
      working-directory: ./
      run: |
        python -m src.train
        python -m src.quantize
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: models
        path: models/

  build_and_test_container:
    needs: train_and_quantize
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: models
        path: models/
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Docker image
      run: docker build -t mlops-major .
    - name: Run container and test predictions
      run: |
        docker run --rm mlops-major